name: Deploy

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform apply
        run: |
          COMMIT=$(echo "${GITHUB_SHA::8}")
          export TF_VAR_commit=$(echo "$COMMIT") 
          cd terraform/
          terraform init
          terraform plan
          terraform apply -auto-approve
          echo "Done!"